apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.volcano.sh
spec:
  group: scheduling.volcano.sh
  names:
    kind: Queue
    plural: queues
    shortNames:
      - q
      - queue-v1beta1
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            weight:
              format: int32
              type: integer
            capability:
              type: object
          type: object
        status:
          properties:
            state:
              type: string
            unknown:
              format: int32
              type: integer
            pending:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
            inqueue:
              format: int32
              type: integer
          type: object
      type: object
  version: v1beta1
  subresources:
    status: {}
